configs:
  dbsync_config.json:
    file: ./dbsync-config.json
networks:
  dbsync:
    external: true
    name: dbsync
secrets:
  dbsync_db_root_password:
    external: true
    name: dbsync_db_root_password
  dbsync_mainnet_db:
    external: true
    name: dbsync_mainnet_db
  dbsync_preprod_db:
    external: true
    name: dbsync_preprod_db
  dbsync_preview_db:
    external: true
  dbsync_sanchonet_db:
    external: true
  postgres_password:
    external: true
    name: dbsync_db_user_password
  postgres_user:
    external: true
    name: dbsync_db_user
services:
  preview2:
    configs:
    - source: dbsync_config.json
      target: /run/configs/dbsync2_config.json
    deploy:
      labels:
        co_elastic_logs/enable: 'false'
      placement:
        constraints:
        - node.labels.dbsync2 == true
      restart_policy:
        condition: on-failure
        delay: 15s
    environment:
      DB_SYNC_CONFIG: /run/configs/dbsync2_config.json
      DISABLE_CACHE: ''
      DISABLE_EPOCH: ''
      DISABLE_LEDGER: ''
      NETWORK: preview
      POSTGRES_HOST: postgres2
      POSTGRES_PORT: 5432
    image: ghcr.io/intersectmbo/cardano-db-sync:13.6.0.4
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 10m
    secrets:
    - postgres_user
    - source: dbsync_preview_db
      target: postgres_db
    - postgres_password
    volumes:
    - /srv/cardano/cardano_preview-dbsync/_data/:/var/lib/cexplorer
    - cardano_preview-ipc:/node-ipc
version: '3.9'
volumes:
  cardano_mainnet-ipc:
    external: true
  cardano_preprod-ipc:
    external: true
  cardano_preview-ipc:
    external: true
  cardano_sanchonet-ipc:
    external: true
  postgres:
    external: true
    name: dbsync_postgres
